# ./docker-compose.yml
# Just chill
version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: .
    image: apache2
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
